[package]
name = "test-zlib-gzip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "compression"
path = "compression.rs"

[dependencies]
flate2 = "1.0.30"
